### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by kibokura056** [Bokuchin/SwitchProconGyroMouse#2]
Proコンが送信するバイトデータの内訳(例えば、X軸のジャイロセンサーの値はどこに含まれているかなど)はどこから入手致しましたか？
私も現在Pythonで開発中です。教えていただけたら幸いです。

**Comment by Bokuchin** [comment]
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md
↑このリンク先の↓この部分や
![image](https://user-images.githubusercontent.com/73187236/151227976-282f096f-04c1-4a8e-84c1-1160e3459829.png)

↓このリンク先で入手致しました。
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/imu_sensor_notes.md

ご参考になれば幸いです。

**Comment by kibokura056** [comment]
有難うございます。参考にさせていただきます。
